"""added category_id to search table

Revision ID: 066567a70f83
Revises: 
Create Date: 2019-11-13 17:25:19.408540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066567a70f83'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search', sa.Column('category_id', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search', 'category_id')
    # ### end Alembic commands ###
