"""empty message

Revision ID: 0ace66b7315f
Revises: f54e7eb48bd0
Create Date: 2019-10-17 16:03:28.029734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ace66b7315f'
down_revision = 'f54e7eb48bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('max_price', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('min_price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'min_price')
    op.drop_column('results', 'max_price')
    # ### end Alembic commands ###
