"""empty message

Revision ID: a4087faf2d1f
Revises: d279769dab13
Create Date: 2019-09-13 14:25:30.576427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4087faf2d1f'
down_revision = 'd279769dab13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('avg_shipping_price', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('median_price', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('top_rated_listing', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('total_watch_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'total_watch_count')
    op.drop_column('results', 'top_rated_listing')
    op.drop_column('results', 'median_price')
    op.drop_column('results', 'avg_shipping_price')
    # ### end Alembic commands ###
