"""empty message

Revision ID: d279769dab13
Revises: 
Create Date: 2019-09-13 11:23:09.136397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd279769dab13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('avg_price', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('largest_cat_count', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('largest_cat_name', sa.String(length=200), nullable=True))
    op.add_column('results', sa.Column('largest_sub_count', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('largest_sub_name', sa.String(length=200), nullable=True))
    op.add_column('results', sa.Column('pages_wanted', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('returned_count', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('top_rated_percent', sa.Float(), nullable=True))
    op.add_column('results', sa.Column('top_seller', sa.String(length=200), nullable=True))
    op.add_column('results', sa.Column('top_seller_count', sa.Integer(), nullable=True))
    op.add_column('results', sa.Column('total_entries', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('results', 'total_entries')
    op.drop_column('results', 'top_seller_count')
    op.drop_column('results', 'top_seller')
    op.drop_column('results', 'top_rated_percent')
    op.drop_column('results', 'returned_count')
    op.drop_column('results', 'pages_wanted')
    op.drop_column('results', 'largest_sub_name')
    op.drop_column('results', 'largest_sub_count')
    op.drop_column('results', 'largest_cat_name')
    op.drop_column('results', 'largest_cat_count')
    op.drop_column('results', 'avg_price')
    # ### end Alembic commands ###
