"""added recurring search tbales

Revision ID: d73d003844a5
Revises: 066567a70f83
Create Date: 2019-11-18 19:13:52.937352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73d003844a5'
down_revision = '066567a70f83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recurring',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['search.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recurring_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recurring_id', sa.Integer(), nullable=True),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('time_searched', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recurring_id'], ['recurring.id'], ),
    sa.ForeignKeyConstraint(['result_id'], ['results.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_ids_time_searched'), 'recurring_ids', ['time_searched'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recurring_ids_time_searched'), table_name='recurring_ids')
    op.drop_table('recurring_ids')
    op.drop_table('recurring')
    # ### end Alembic commands ###
