"""empty message

Revision ID: f54e7eb48bd0
Revises: 
Create Date: 2019-10-07 15:07:51.113728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f54e7eb48bd0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('results', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'results', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'results', type_='foreignkey')
    op.drop_column('results', 'user_id')
    # ### end Alembic commands ###
